language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  matrix:
    - DJANGO="Django>=1.4,<1.5"
    - DJANGO="Django>=1.5,<1.6"
    - DJANGO="Django>=1.6,<1.7"
    - DJANGO="https://www.djangoproject.com/download/1.7b1/tarball/"
    - DJANGO="-e git+git://github.com/django/django.git#egg=Django"
install:
  - pip install $DJANGO
  - pip install coveralls
  - make dev
script:
  - make lint
  - py.test tests/*.py --cov django_sudo --cov-report term-missing
after_success:
  - coveralls
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="https://www.djangoproject.com/download/1.7b1/tarball/"
    - python: "2.6"
      env: DJANGO="-e git+git://github.com/django/django.git#egg=Django"
