language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  matrix:
    - DJANGO="Django>=1.4,<1.5"
    - DJANGO="Django>=1.5,<1.6"
    - DJANGO="Django>=1.6,<1.7"
    - DJANGO="https://www.djangoproject.com/download/1.7b1/tarball/"
install:
  - pip install $DJANGO
  - pip install coveralls
  - pip install -r dev-requirements.txt
script:
  - inv test
after_success:
  - coveralls
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="https://www.djangoproject.com/download/1.7b1/tarball/"
    - python: "3.2"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.3"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.4"
      env: DJANGO="Django>=1.4,<1.5"
